name: push to hatena blog

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - "entries/**"

jobs:
  push:
    uses: hatena/hatenablog-workflows/.github/workflows/push.yaml@ce4c0e01255ad9348842e5ce09809c3ec499e43d # v2.0.5
    with:
      local_root: "entries"
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
